#!/bin/sh

# Compiles the project that contains the current or given directory.
#
# Supports Gradle, Maven, and Make projects.  If no buildfile is found
# at the top level, searches at (only) the next level down.
#
# The exit status is failure if any build fails.  If no buildfile is
# found and ERR_IF_NO_BUILDFILE is set to a non-empty value, then the
# exit status is failure.
#
# Usage:
#   compile-project [--clean] [<directory>]
#
# If --clean is passed, then the project is cleaned before being compiled.
# If variable GRADLE_ASSEMBLE_FLAGS is defined, it is passed to `gradlew assemble` or `gradle assemble`.
# If variable MVN_COMPILE_FLAGS is defined, it is passed to `mvnw compile` or `mvn compile`.
# If variable MAKE_FLAGS is defined, it is passed to `make`.
# If variable ERR_IF_NO_BUILDFILE is non-empty, the script fails if no buildfile is found.
#
# This command does not need to be run in the top-level directory of the project;
# it will discover the top-level directory on its own and run the command there.

# TODO: Handle other build systems too, such as Ant.
# TODO: Have a list of per-directory or per-repository commands, to override the default.

if [ "$#" -ge 1 ]; then
  if [ "$1" = "--clean" ]; then
    CLEAN="$1"
    shift
  fi
fi

# SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
SCRIPT_NAME="$(basename -- "$0")"

# $toplevel does not have a trailing "/" character
if [ "$#" -eq 0 ]; then
  if toplevel="$(git rev-parse --show-toplevel 2> /dev/null)"; then
    echo "Running ${SCRIPT_NAME} in $toplevel, called from $(pwd)"
  else
    toplevel=$(pwd)
    echo "Running ${SCRIPT_NAME} in $toplevel"
  fi
elif [ "$#" -eq 1 ]; then
  toplevel="$1"
  echo "Running ${SCRIPT_NAME} in $toplevel"
else
  echo "Usage: ${SCRIPT_NAME} [--clean] [<directory>]" >&2
  exit 1
fi

# Compiles the project in directory $1, if that directory contains a buildfile.
# Returns the status code of the build command, or 0 if no buildfile was found.
# Sets buildfile_in_directory to 1 if a buildfile was found, to 0 if not.
# (A status code cannot indicate "no buildfile was found", because every status
# code is a status code that some build command might exit with.)
compile_in_directory() {
  dir="$1"
  buildfile_in_directory=1

  if [ -f "$dir/gradlew" ]; then
    if [ -n "$CLEAN" ]; then
      "$dir/gradlew" --project-dir "$dir" clean -q < /dev/null
    fi
    # shellcheck disable=SC2086 # Word splitting is desirable here.
    "$dir/gradlew" --project-dir "$dir" assemble -q ${GRADLE_ASSEMBLE_FLAGS} < /dev/null
    return $?
  elif [ -f "$dir/build.gradle" ]; then
    if [ -n "$CLEAN" ]; then
      gradle --project-dir "$dir" clean -q < /dev/null
    fi
    # shellcheck disable=SC2086 # Word splitting is desirable here.
    gradle --project-dir "$dir" assemble -q ${GRADLE_ASSEMBLE_FLAGS} < /dev/null
    return $?
  elif [ -f "$dir/mvnw" ]; then
    if [ -n "$CLEAN" ]; then
      (cd "$dir" && ./mvnw -q clean)
    fi
    # shellcheck disable=SC2086 # Word splitting is desirable here.
    (cd "$dir" && ./mvnw -q compile ${MVN_COMPILE_FLAGS})
    return $?
  elif [ -f "$dir/pom.xml" ]; then
    if [ -n "$CLEAN" ]; then
      (cd "$dir" && mvn -q clean)
    fi
    # shellcheck disable=SC2086 # Word splitting is desirable here.
    (cd "$dir" && mvn -q compile ${MVN_COMPILE_FLAGS})
    return $?
  elif [ -f "$dir/Makefile" ]; then
    if [ -n "$CLEAN" ]; then
      (cd "$dir" && make clean)
    fi
    # shellcheck disable=SC2086 # Word splitting is desirable here.
    (cd "$dir" && make ${MAKE_FLAGS})
    return $?
  else
    # No buildfile was found.
    buildfile_in_directory=0
    return 0
  fi
}

compile_in_directory "$toplevel"
result=$?

if [ "$buildfile_in_directory" = 1 ]; then
  # A buildfile was found; exit with the exit code of the compilation step.
  exit $result
else
  # Call compile_in_directory in subdirectories.
  buildfile_found=0
  for subdir in "$toplevel"/*/; do
    compile_in_directory "$subdir"
    result=$?
    if [ "$buildfile_in_directory" = 0 ]; then
      continue
    fi
    buildfile_found=1
    if [ "$result" -ne 0 ]; then
      exit $result
    fi
  done
  if [ "$buildfile_found" = 0 ] && [ -n "$ERR_IF_NO_BUILDFILE" ]; then
    echo "${SCRIPT_NAME} did nothing in $(pwd)" >&2
    exit 1
  fi
fi
