#!/bin/sh

# Checks out an existing branch of the current repository,
# in a sibling directory named REPONAME-branch-BRANCHNAME/.
#
# Usage:
#   git-checkout-branch BRANCHNAME

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
SCRIPT_NAME="$(basename -- "$0")"

if [ "$#" -ne 1 ]; then
  echo "Usage: ${SCRIPT_NAME} BRANCHNAME" >&2
  exit 1
fi

STARTDIR="${PWD}"

if ! cd "$(git rev-parse --show-toplevel 2>&1)"; then
  echo "${SCRIPT_NAME}: Cannot determine top-level directory of git repository"
  git rev-parse --show-toplevel
  cd "${STARTDIR}" || exit 1
  exit 1
fi

REPO=$(basename "$(pwd)")
BRANCHNAME="$1"
BRANCHNOSLASH=$(echo "${BRANCHNAME}" | sed -e "s:/:-:g")
BRANCHDIR=$(realpath "../${REPO%%-branch-*}-branch-${BRANCHNOSLASH}")
TMPDIR="${BRANCHDIR}-TMP"

git pull -q > /dev/null 2>&1 || true

if [ -z "$(git branch -r --list "origin/${BRANCHNAME}")" ]; then
  if ! git ls-remote --exit-code origin "${BRANCHNAME}"; then
    echo "${SCRIPT_NAME}: ERROR: branch ${BRANCHNAME} does not exist."
    cd "${STARTDIR}" || exit 1
    exit 1
  fi
fi

if [ -e "${BRANCHDIR}" ]; then
  echo "${SCRIPT_NAME}: ERROR: directory exists: ${BRANCHDIR}"
  cd "${STARTDIR}" || exit 1
  exit 1
fi
if [ -e "${TMPDIR}" ]; then
  echo "${SCRIPT_NAME}: ERROR: directory exists: ${TMPDIR}"
  cd "${STARTDIR}" || exit 1
  exit 1
fi

if ! \cp -Rp . "${TMPDIR}"; then
  echo "${SCRIPT_NAME}: ERROR: cannot copy $(pwd) to ${TMPDIR}"
  cd "${STARTDIR}" || exit 1
  exit 1
fi
if ! (cd "${TMPDIR}" && git checkout "${BRANCHNAME}" -q); then
  echo "${SCRIPT_NAME}: ERROR in: (cd \"${TMPDIR}\" && git checkout \"${BRANCHNAME}\" -q)"
  cd "${STARTDIR}" || exit 1
  exit 1
fi

git pull -q > /dev/null 2>&1 || true

if ! mv "${TMPDIR}" "${BRANCHDIR}"; then
  echo "${SCRIPT_NAME}: ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
  cd "${STARTDIR}" || exit 1
  exit 1
fi

echo "Success: checked out to ${BRANCHDIR}"

cd "${STARTDIR}" || exit 1
