#!/bin/sh

case "${IS_DELETED_BRANCH_SSH_BATCH_OPTION}" in
  '-o BatchMode=yes')
    exec "${IS_DELETED_BRANCH_GIT_SSH}" -o BatchMode=yes "$@"
    ;;
  -batch)
    exec "${IS_DELETED_BRANCH_GIT_SSH}" -batch "$@"
    ;;
  *)
    echo 'is-deleted-branch-ssh-wrapper: invalid batch option' >&2
    exit 1
    ;;
esac
